name: exam
description: "A series of tests for new members of a team"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  args: ^2.6.0
  mason_logger: ^0.3.2
  yaml: ^3.1.3
  pocketbase: ^0.21.0
  yaml_magic: ^1.0.6

flutter:
  uses-material-design: true

executables:
  exam:
